### ISSUE TITLE
404 - With JavaScript Examples

### ISSUE THREAD

**Issue by rmcveigh** [IHTSDO/SNOMED-in-5-minutes#14]
I received nothing but 404s from the server when attempting to use the JavaScript examples. I was able to resolve this by setting the `baseUrl` to `http://browser.ihtsdotools.org/snowstorm/snomed-ct/v2/browser`, change the `edition` to `MAIN`, removing the `version` variable from all the URLs, And updating the URL Params to:
* `$scope.findByQueryUrl = baseUrl + '/' + edition + '/descriptions?term=' + encodeURIComponent(query) + '&limit=50&conceptActive=true&lang=english&conceptActive=true&skipTo=0&returnLimit=100';`
* `$scope.findByConceptIdUrl = baseUrl + '/' + edition + '/concepts/' + query;`
* `$scope.findByQueryWithFilterUrl = baseUrl + '/' + edition + '/descriptions?term=' + encodeURIComponent(query) + '&limit=50&lang=english&conceptActive=true&skipTo=0&returnLimit=100&semanticTag=' + encodeURIComponent(filter);`

**Comment by kaicode** [comment]
Hi @rmcveigh, yes last week we replaced the API for this and the public SNOMED CT browser. It's on our todo list to update all the SNOMED in 5 minutes examples which will all need updating in order to work. Some of the contributors who wrote the examples have moved on so we welcome contributions from those who can.
Thanks for flagging this 👍

**Comment by rmcveigh** [comment]
Not sure if it helps, but I created a quick codepen in mostly vanilla javascript that shows the fix. https://codepen.io/rmcveigh/full/RXQKKq

**Comment by rorydavidson** [comment]
@rmcveigh we're in the process of upgrading these examples, and you can see those ongoing changes, including Javascript, in the develop branch at the moment.

**Comment by rorydavidson** [comment]
The examples have now been updated so closing this issue.
