### ISSUE TITLE
Unnecessary slash end of baseUrl

### ISSUE THREAD

**Issue by blaskodaniel** [IHTSDO/SNOMED-in-5-minutes#16]
Hi, I noticed a small mistake here:
https://github.com/IHTSDO/SNOMED-in-5-minutes/blob/ed36b9dec27a397b0237524890021d351d5347d0/javascript-examples/app.js#L10

This may cause a CORS error. It should be deleted the last slash:
var baseUrl = "https://browser.ihtsdotools.org/snowstorm/snomed-ct/v2/"; 
=> 
var baseUrl = "https://browser.ihtsdotools.org/snowstorm/snomed-ct/v2";

**Comment by kaicode** [comment]
Thanks @blaskodaniel, that's fixed now.
