### ISSUE TITLE
Examples now fail

### ISSUE THREAD

**Issue by mgraauw** [IHTSDO/SNOMED-in-5-minutes#18]
The example code fails.
URL's like:
https://browser.ihtsdotools.org/snowstorm/snomed-ct/v2/browser/MAIN/2019-07-31/concepts/109152007
which used to retrieve some json, now redirect to:
https://browser.ihtsdotools.org/snowstorm/snomed-ct/swagger-ui.html
Which has a field for an API key.

Apparently something server-side has changed which is not reflected in the examples here.

**Comment by kaicode** [comment]
Hi @mgraauw, thanks for spotting this. Yes, we just changed the API path of our public Snowstorm terminology server which serves these requests.
The `/v2` part of the path has been removed.
The following is the new version of your example URL - https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/109152007

I will update all examples today.

**Comment by mgraauw** [comment]
Thanks for the incredibly speedy response! Yes, that helps.

**Comment by kaicode** [comment]
I've updated all examples in master. Please pull 👍 😸
