### ISSUE TITLE
Same return from the api

### ISSUE THREAD

**Issue by Orneyfish** [IHTSDO/SNOMED-in-5-minutes#20]
Well I tried to use this but whenever I use get concepts by a string it always returns the same

**Comment by rorydavidson** [comment]
Hi @Orneyfish , sorry for the very late response. What were you getting back in your response?

**Comment by Orneyfish** [comment]
Hey it's okay the problem is solved. Thanks a lot for your concern.

**Comment by ddbhasin** [comment]
Hi @Orneyfish how did you solve the issue? I am getting the same response when I use get concepts by string irrespective of the string. It always returns the number 471023

**Comment by Orneyfish** [comment]
I think you need to map the number again from the dataset by doing another
sql call as the number is mapped with particular entities.
