### ISSUE TITLE
Do we need a license to access these API endpoints directly from an application?

### ISSUE THREAD

**Issue by HenrikJoreteg** [IHTSDO/SNOMED-in-5-minutes#22]
I'm looking for an API to turn a term such as "headaches" into a codeable concept when describing patient conditions in an application.

What's not clear to me after reviewing this is whether or not the API endpoints in these examples are meant for public use or if we need some kind of license to access them. Sorry if this is not the right place to ask, but I'm struggling to find this info.

Overall, volume of requests should be quite low. I doubt we would hit any sort of rate limiting.

Thanks in advance for any guidance!

**Comment by rorydavidson** [comment]
@HenrikJoreteg the APIs you see here can be used in development or prototyping, although volume and usage are monitored. 

However, we always recommend to not use in any production system as we do not guarantee the APIs availability or uptime. It would be best if you can use our open-source [Snowstorm SNOMED CT terminology server](https://github.com/IHTSDO/snowstorm) locally to ensure you always have the access you need.
