### ISSUE TITLE
Python example needs to be updated

### ISSUE THREAD

**Issue by priyaranjan-tokachichu** [IHTSDO/SNOMED-in-5-minutes#6]
The Python example uses 'fsn' for fully specified name. It should be updated to 'fullySpecifiedName'.
```
def getConceptById(id):
    url = baseUrl + edition + '/' + version + '/concepts/' + id
    response = urlopen(url).read()
    data = json.loads(response.decode('utf-8'))
    #The following doesn't work
    #print (data['fsn'])
    #The following works
    print (data['fullySpecifiedName'])
```

**Comment by rorydavidson** [comment]
Hi, thanks for pointing this out. This is because the newer version of the API uses fullySpecifedName. For now, all the baseUrl's have been redirected to v1 in this repo.
