### ISSUE TITLE
Unable to run the API

### ISSUE THREAD

**Issue by jagadeeshpuvvula** [IHTSDO/SNOMED-in-5-minutes#8]
Error: urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

**Comment by me2resh** [comment]
@jagadeeshpuvvula Which example were you using? Or you were using another tool?

**Comment by kaicode** [comment]
Closing as inactive. Feel free to reopen if there is more information.
